version: '3.9'
services:
  openems-ui:
    build: 
      context: ./openems-ui
    image: openems-ui:latest

  openems-backend:
    build: 
      context: ./openems-backend
    image: openems-backend:latest

  openems-edge:
    build: 
      context: ./openems-edge
    image: openems-edge:latest

  openems-database:
    build: 
      context: ./openems-database
    image: openems-db:latest
    ports: 
      - "5432:5432"

  odoo:
    build: 
      context: ./odoo
    image: odoo:latest

  odoo-database:
    build: 
      context: ./odoo-database
    image: odoo-db:latest
    ports: 
      - "5433:5432"
   