version: '3.9'
services:
  openems-ui:
    build: 
      context: ./openems-ui
    image: openems-ui:latest
    networks:
      - openems-network

  openems-backend:
    build: 
      context: ./openems-backend
    image: openems-backend:latest
    environment:
      DB_HOST: openems-database  # Assumes the PostgreSQL service is named openems-database
      DB_PORT: "5432"
      DB_NAME: openemsdb
      DB_USER: postgres
      DB_PASSWORD: myopenemspassword
    depends_on:
      - openems-database

  openems-edge:
    build: 
      context: ./openems-edge
    image: openems-edge:latest
    

  openems-database:
    build: 
      context: ./openems-database
    image: openems-db:latest
    ports: 
      - "5432:5432"
 

  odoo:
    build: 
      context: ./odoo
    image: odoo:latest
    ports:
      - "8069:8069"
    depends_on:
      - odoo-database
    environment:
      HOST: odoo-database
      PORT: "5433"
      USER: odoo
      PASSWORD: myodoo

  odoo-database:
    build: 
      context: ./odoo-database
    image: odoo-db:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: myodoo
      POSTGRES_DB: odoodb
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
