# Use Postgres 15 as the base image
FROM postgres:15

# Set the default user and password for PostgreSQL
ENV POSTGRES_USER=odoo
ENV POSTGRES_PASSWORD=odoo

# Set the default database
ENV POSTGRES_DB=postgres

# Expose the default port for PostgreSQL
EXPOSE 5432
