# Use Odoo 16.0 as the base image

FROM 470298448112.dkr.ecr.us-east-1.amazonaws.com/odoo16.00:latest

EXPOSE 8069


# COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh


# ENTRYPOINT ["/entrypoint.sh"]
# CMD ["odoo"]