#!/usr/bin/env bash
# Generate docker-compose.override.yml with OpenEMS Edge "sites".
#
# Flat mode:     ./scale-edges.sh 5
#                  -> edge0..edge4 (no cluster label)
# Cluster mode:  ./scale-edges.sh bronx=3 queens=2
#                  -> bronx-01..bronx-03, queens-01..queens-02
#                     each tagged with CLUSTER=<name> (stored in Core.Meta.placeName)
#
# Edge-IDs must end in digits so the backend keeps the readable name (e.g.
# "bronx-02"); the trailing number also scales that site's simulated PV.
set -e
cd "$(dirname "$0")"

OUT=docker-compose.override.yml
[ $# -eq 0 ] && set -- 5

emit_edge() { # $1=edge-id  $2=cluster-label (may be empty)
  local id="$1" cluster="$2"
  cat <<EOF
  $id:
    build:
      context: ./edge
      args:
        OPENEMS_VERSION: "2026.6.0"
    image: openems-edge:2026.6.0
    container_name: openems-edge-$id
    depends_on:
      - openems-backend
    environment:
      EDGE_ID: "$id"
      BACKEND_URI: "ws://openems-backend:8081"
EOF
  [ -n "$cluster" ] && echo "      CLUSTER: \"$cluster\""
  echo "    restart: unless-stopped"
}

ids=""
{
  echo "# AUTO-GENERATED by scale-edges.sh -- do not edit by hand."
  echo "services:"
  if [ $# -eq 1 ] && printf '%s' "$1" | grep -qE '^[0-9]+$'; then
    # flat mode
    i=0
    while [ "$i" -lt "$1" ]; do emit_edge "edge$i" ""; ids="$ids edge$i"; i=$((i+1)); done
  else
    # cluster mode: name=count ...
    # Numbering is GLOBAL across clusters (bronx-01, bronx-02, queens-03, ...)
    # because the InfluxDB storage tags each edge by the NUMBER in its id
    # (parseNumberFromName), so duplicate numbers across clusters would collide.
    g=1
    for spec in "$@"; do
      name="${spec%%=*}"; count="${spec##*=}"
      case "$count" in ''|*[!0-9]*) echo "bad spec: $spec (use name=count)" >&2; exit 1 ;; esac
      i=1
      while [ "$i" -le "$count" ]; do
        id=$(printf '%s-%02d' "$name" "$g")
        emit_edge "$id" "$name"; ids="$ids $id"; i=$((i+1)); g=$((g+1))
      done
    done
  fi
} > "$OUT"

n=$(echo $ids | wc -w | tr -d ' ')
csv=$(echo $ids | tr ' ' ',')
echo "wrote $OUT: $n edges ->$ids"
echo "next:  docker compose up -d --build"
echo "watch: python3 probe_backend.py $csv"
