# Application credentials — generated by Terraform, stored in Secrets Manager,
# injected into containers via ECS `secrets`. Nothing here lands in tfvars,
# task-definition JSON, or images.
#
# db_password   — RDS master password; Odoo and the backend (Metadata.Odoo
#                 direct Postgres reads) both authenticate with it.
# odoo_password — the Odoo application admin password the backend uses for
#                 XML-RPC calls. The one-time Odoo DB init (see the PR-A
#                 runbook) must set the Odoo admin user to this value.

resource "random_password" "db" {
  length  = 24
  special = false # alphanumeric only: safe in connection strings and sed
}

resource "random_password" "odoo_admin" {
  length  = 24
  special = false
}

resource "aws_secretsmanager_secret" "app_credentials" {
  name        = "${var.project_name}-${var.environment}-app-credentials"
  description = "OpenEMS stack credentials (RDS + Odoo admin)"
}

resource "aws_secretsmanager_secret_version" "app_credentials" {
  secret_id = aws_secretsmanager_secret.app_credentials.id
  secret_string = jsonencode({
    db_password   = random_password.db.result
    odoo_password = random_password.odoo_admin.result
  })
}
